export PS1=$'\[\033[1;33m\]\u\[\033[1;32m\]@\h\[\033[1;36m\]:\W\[\033[1;37m\]\$\[\033[0m\]'     
##########################################
alias ls='ls --color=auto'
##########################################
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib/"
export PYTHONPATH="$PYTHONPATH:/home/user"
