#!/bin/bash -l

#SBATCH --ntasks 1
#SBATCH -J pipeline_runner_cosma
#SBATCH --array=1-4
#SBATCH -o ../output/pipeline_runner_cosma_output.%A.%a.out
#SBATCH -e ../output/pipeline_runner_cosma_error.%A.%a.err
#SBATCH -p cosma # also cordelia
#SBATCH -A durham
#SBATCH -t 1:00:00   # longest job
#SBATCH --mail-type=END                          # notifications for job done & fail
#SBATCH --mail-user=email@durham.ac.uk

module purge
module load python/3.6.5
source /cosma/home/durham/pdtw24/PyAutoLens/bin/activate

# Run the program, note $SLURM_ARRAY_TASK_ID is set to the array number.

python3 $WORKSPACE/runners/slacs_runner_cosma.py $SLURM_ARRAY_TASK_ID