from autoarray.operators.inversion import inversions
from autoarray.operators import transformer as trans
import autolens as al
from autolens.fit.fit import ImagingFit, InterferometerFit
import numpy as np
import pytest

from test_autoastro.mock.mock_profiles import MockLightProfile


class TestImagingFit:
    class TestFitProperties:
        def test__total_inversions(self, masked_imaging_7x7):

            g0 = al.Galaxy(redshift=0.5)

            g1 = al.Galaxy(redshift=1.0)

            g2 = al.Galaxy(redshift=2.0)

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            assert fit.total_inversions == 0

            g2 = al.Galaxy(
                redshift=2.0,
                pixelization=al.pix.Rectangular(),
                regularization=al.reg.Constant(),
            )

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            assert fit.total_inversions == 1

            g0 = al.Galaxy(
                redshift=0.5,
                pixelization=al.pix.Rectangular(),
                regularization=al.reg.Constant(),
            )

            g1 = al.Galaxy(
                redshift=1.0,
                pixelization=al.pix.Rectangular(),
                regularization=al.reg.Constant(),
            )

            g2 = al.Galaxy(
                redshift=2.0,
                pixelization=al.pix.Rectangular(),
                regularization=al.reg.Constant(),
            )

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            assert fit.total_inversions == 3

    class TestLikelihood:
        def test__1x2_image__no_psf_blurring__tracing_fits_data_with_chi_sq_5(self):
            # The image plane image generated by the galaxy is [1.0, 1.0]

            # Thus the chi squared is 4.0**2.0 + 3.0**2.0 = 25.0

            psf = al.kernel.manual_2d(
                array=(np.array([[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 0.0]])),
                pixel_scales=1.0,
            )

            imaging = al.imaging(
                image=5.0 * al.array.ones(shape_2d=(3, 4)),
                pixel_scales=1.0,
                psf=psf,
                noise_map=al.array.ones(shape_2d=(3, 4)),
            )
            imaging.image[6] = 4.0

            mask = al.mask.manual(
                mask_2d=np.array(
                    [
                        [True, True, True, True],
                        [True, False, False, True],
                        [True, True, True, True],
                    ]
                ),
                pixel_scales=1.0,
                sub_size=1,
            )

            masked_imaging_7x7 = al.masked_imaging(imaging=imaging, mask=mask)

            # Setup as a ray trace instance, using a light profile for the lens

            g0 = al.Galaxy(
                redshift=0.5, light_profile=MockLightProfile(value=1.0, size=2)
            )
            tracer = al.Tracer.from_galaxies(galaxies=[g0])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            assert (
                fit.mask
                == np.array(
                    [
                        [True, True, True, True],
                        [True, False, False, True],
                        [True, True, True, True],
                    ]
                )
            ).all()

            assert (
                fit.image.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 5.0, 4.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.noise_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.model_image.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.residual_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 4.0, 3.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.normalized_residual_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 4.0, 3.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.chi_squared_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 16.0, 9.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert fit.chi_squared == 25.0
            assert fit.reduced_chi_squared == 25.0 / 2.0
            assert fit.noise_normalization == (2.0 * np.log(2 * np.pi * 1.0 ** 2.0))
            assert fit.likelihood == -0.5 * (
                25.0 + 2.0 * np.log(2 * np.pi * 1.0 ** 2.0)
            )

        def test__1x2_image__include_psf_blurring__tracing_fits_data_with_chi_sq_4(
            self
        ):
            # This PSF changes the blurred image plane image from [1.0, 1.0] to [1.0, 5.0]

            # Thus, the chi squared is 4.0**2.0 + 0.0**2.0 = 16.0

            psf = al.kernel.manual_2d(
                array=(np.array([[0.0, 0.0, 0.0], [0.0, 1.0, 3.0], [0.0, 0.0, 0.0]])),
                pixel_scales=1.0,
            )

            imaging = al.imaging(
                5.0 * al.array.ones(shape_2d=(3, 4)),
                pixel_scales=1.0,
                psf=psf,
                noise_map=al.array.ones(shape_2d=(3, 4)),
            )
            imaging.image[6] = 4.0

            mask = al.mask.manual(
                mask_2d=np.array(
                    [
                        [True, True, True, True],
                        [True, False, False, True],
                        [True, True, True, True],
                    ]
                ),
                pixel_scales=1.0,
                sub_size=1,
            )

            masked_imaging_7x7 = al.masked_imaging(imaging=imaging, mask=mask)

            # Setup as a ray trace instance, using a light profile for the lens

            g0 = al.Galaxy(
                redshift=0.5, light_profile=MockLightProfile(value=1.0, size=2)
            )
            tracer = al.Tracer.from_galaxies(galaxies=[g0])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            assert (
                fit.mask
                == np.array(
                    [
                        [True, True, True, True],
                        [True, False, False, True],
                        [True, True, True, True],
                    ]
                )
            ).all()

            assert (
                fit.image.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 5.0, 4.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.noise_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.model_image.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 4.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.residual_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 4.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.normalized_residual_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 4.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.chi_squared_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 16.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert fit.chi_squared == 16.0
            assert fit.reduced_chi_squared == 16.0 / 2.0
            assert fit.noise_normalization == (2.0 * np.log(2 * np.pi * 1.0 ** 2.0))
            assert fit.likelihood == -0.5 * (
                16.0 + 2.0 * np.log(2 * np.pi * 1.0 ** 2.0)
            )

        def test_hyper_galaxy_changes_noise_above_from_1_to_2__reflected_in_likelihood(
            self
        ):
            # This PSF changes the blurred image plane image from [1.0, 1.0] to [1.0, 5.0]

            # Thus, the chi squared is 4.0**2.0 + 0.0**2.0 = 16.0

            # The hyper_galaxies galaxy increases the noise in both pixels by 1.0, to 2.0.

            # This reduces the chi squared to 2.0 instead of 4.0

            psf = al.kernel.manual_2d(
                array=(np.array([[0.0, 0.0, 0.0], [0.0, 1.0, 3.0], [0.0, 0.0, 0.0]])),
                pixel_scales=1.0,
            )

            imaging = al.imaging(
                5.0 * al.array.ones(shape_2d=(3, 4)),
                pixel_scales=1.0,
                psf=psf,
                noise_map=al.array.ones(shape_2d=(3, 4)),
            )
            imaging.image[6] = 4.0

            mask = al.mask.manual(
                mask_2d=np.array(
                    [
                        [True, True, True, True],
                        [True, False, False, True],
                        [True, True, True, True],
                    ]
                ),
                pixel_scales=1.0,
                sub_size=1,
            )

            masked_imaging_7x7 = al.masked_imaging(imaging=imaging, mask=mask)

            # Setup as a ray trace instance, using a light profile for the lens

            g0 = al.Galaxy(
                redshift=0.5,
                light_profile=MockLightProfile(value=1.0, size=2),
                hyper_galaxy=al.HyperGalaxy(
                    contribution_factor=1.0, noise_factor=1.0, noise_power=1.0
                ),
                hyper_model_image=al.array.ones(shape_2d=(1, 2)),
                hyper_galaxy_image=al.array.ones(shape_2d=(1, 2)),
                hyper_minimum_value=0.0,
            )

            tracer = al.Tracer.from_galaxies(galaxies=[g0])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            assert (
                fit.mask
                == np.array(
                    [
                        [True, True, True, True],
                        [True, False, False, True],
                        [True, True, True, True],
                    ]
                )
            ).all()

            assert (
                fit.image.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 5.0, 4.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.noise_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 2.0, 2.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.model_image.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 4.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.residual_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 4.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.normalized_residual_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 2.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.chi_squared_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 4.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert fit.chi_squared == 4.0
            assert fit.reduced_chi_squared == 4.0 / 2.0
            assert fit.noise_normalization == (2.0 * np.log(2 * np.pi * 2.0 ** 2.0))
            assert fit.likelihood == -0.5 * (4.0 + 2.0 * np.log(2 * np.pi * 2.0 ** 2.0))

        def test__hyper_image_changes_background_sky__reflected_in_likelihood(self):

            psf = al.kernel.manual_2d(
                array=(np.array([[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 0.0]])),
                pixel_scales=1.0,
            )

            imaging = al.imaging(
                al.array.full(fill_value=4.0, shape_2d=(3, 4)),
                pixel_scales=1.0,
                psf=psf,
                noise_map=al.array.ones(shape_2d=(3, 4)),
            )
            imaging.image[5] = 5.0

            mask = al.mask.manual(
                mask_2d=np.array(
                    [
                        [True, True, True, True],
                        [True, False, False, True],
                        [True, True, True, True],
                    ]
                ),
                pixel_scales=1.0,
                sub_size=1,
            )

            masked_imaging_7x7 = al.masked_imaging(imaging=imaging, mask=mask)

            # Setup as a ray trace instance, using a light profile for the lens

            g0 = al.Galaxy(
                redshift=0.5, light_profile=MockLightProfile(value=1.0, size=2)
            )
            tracer = al.Tracer.from_galaxies(galaxies=[g0])

            hyper_image_sky = al.hyper_data.HyperImageSky(sky_scale=1.0)

            fit = ImagingFit(
                masked_imaging=masked_imaging_7x7,
                tracer=tracer,
                hyper_image_sky=hyper_image_sky,
            )

            assert (
                fit.mask
                == np.array(
                    [
                        [True, True, True, True],
                        [True, False, False, True],
                        [True, True, True, True],
                    ]
                )
            ).all()

            assert (
                fit.image.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 6.0, 5.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.noise_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.model_image.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.residual_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 5.0, 4.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.normalized_residual_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 5.0, 4.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.chi_squared_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 25.0, 16.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert fit.chi_squared == 41.0
            assert fit.reduced_chi_squared == 41.0 / 2.0
            assert fit.noise_normalization == (2.0 * np.log(2 * np.pi * 1.0 ** 2.0))
            assert fit.likelihood == -0.5 * (
                41.0 + 2.0 * np.log(2 * np.pi * 1.0 ** 2.0)
            )

        def test__hyper_background_changes_background_noise_map__reflected_in_likelihood(
            self
        ):

            psf = al.kernel.manual_2d(
                array=(np.array([[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 0.0]])),
                pixel_scales=1.0,
            )

            imaging = al.imaging(
                5.0 * al.array.ones(shape_2d=(3, 4)),
                pixel_scales=1.0,
                psf=psf,
                noise_map=al.array.ones(shape_2d=(3, 4)),
            )
            imaging.image[6] = 4.0

            mask = al.mask.manual(
                mask_2d=np.array(
                    [
                        [True, True, True, True],
                        [True, False, False, True],
                        [True, True, True, True],
                    ]
                ),
                pixel_scales=1.0,
                sub_size=1,
            )

            masked_imaging_7x7 = al.masked_imaging(imaging=imaging, mask=mask)

            # Setup as a ray trace instance, using a light profile for the lens

            g0 = al.Galaxy(
                redshift=0.5, light_profile=MockLightProfile(value=1.0, size=2)
            )
            tracer = al.Tracer.from_galaxies(galaxies=[g0])

            hyper_background_noise = al.hyper_data.HyperBackgroundNoise(noise_scale=1.0)

            fit = ImagingFit(
                masked_imaging=masked_imaging_7x7,
                tracer=tracer,
                hyper_background_noise=hyper_background_noise,
            )

            assert (
                fit.mask
                == np.array(
                    [
                        [True, True, True, True],
                        [True, False, False, True],
                        [True, True, True, True],
                    ]
                )
            ).all()

            assert (
                fit.image.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 5.0, 4.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.noise_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 2.0, 2.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.model_image.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.residual_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 4.0, 3.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.normalized_residual_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 2.0, 1.5, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert (
                fit.chi_squared_map.in_2d
                == np.array(
                    [[0.0, 0.0, 0.0, 0.0], [0.0, 4.0, 2.25, 0.0], [0.0, 0.0, 0.0, 0.0]]
                )
            ).all()

            assert fit.chi_squared == 6.25
            assert fit.reduced_chi_squared == 6.25 / 2.0
            assert fit.noise_normalization == (2.0 * np.log(2 * np.pi * 2.0 ** 2.0))
            assert fit.likelihood == -0.5 * (
                6.25 + 2.0 * np.log(2 * np.pi * 2.0 ** 2.0)
            )

    class TestCompareToManualProfilesOnly:
        def test___all_lens_fit_quantities__no_hyper_methods(self, masked_imaging_7x7):

            g0 = al.Galaxy(
                redshift=0.5,
                light_profile=al.lp.EllipticalSersic(intensity=1.0),
                mass_profile=al.mp.SphericalIsothermal(einstein_radius=1.0),
            )

            g1 = al.Galaxy(
                redshift=1.0, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            assert masked_imaging_7x7.noise_map.in_2d == pytest.approx(
                fit.noise_map.in_2d
            )

            model_image = tracer.blurred_profile_image_from_grid_and_convolver(
                grid=masked_imaging_7x7.grid,
                convolver=masked_imaging_7x7.convolver,
                blurring_grid=masked_imaging_7x7.blurring_grid,
            )

            assert model_image.in_2d == pytest.approx(fit.model_image.in_2d)

            residual_map = al.util.fit.residual_map_from_data_and_model_data(
                data=masked_imaging_7x7.image, model_data=model_image
            )

            assert residual_map.in_2d == pytest.approx(fit.residual_map.in_2d)

            normalized_residual_map = al.util.fit.normalized_residual_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_imaging_7x7.noise_map
            )

            assert normalized_residual_map.in_2d == pytest.approx(
                fit.normalized_residual_map.in_2d
            )

            chi_squared_map = al.util.fit.chi_squared_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_imaging_7x7.noise_map
            )

            assert chi_squared_map.in_2d == pytest.approx(fit.chi_squared_map.in_2d)

            chi_squared = al.util.fit.chi_squared_from_chi_squared_map(
                chi_squared_map=chi_squared_map
            )

            noise_normalization = al.util.fit.noise_normalization_from_noise_map(
                noise_map=masked_imaging_7x7.noise_map
            )

            likelihood = al.util.fit.likelihood_from_chi_squared_and_noise_normalization(
                chi_squared=chi_squared, noise_normalization=noise_normalization
            )

            assert likelihood == pytest.approx(fit.likelihood, 1e-4)
            assert likelihood == fit.figure_of_merit

        def test___lens_fit_galaxy_model_image_dict__corresponds_to_blurred_galaxy_images(
            self, masked_imaging_7x7
        ):
            g0 = al.Galaxy(
                redshift=0.5,
                light_profile=al.lp.EllipticalSersic(intensity=1.0),
                mass_profile=al.mp.SphericalIsothermal(einstein_radius=1.0),
            )
            g1 = al.Galaxy(
                redshift=1.0, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )
            g2 = al.Galaxy(redshift=1.0)

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            traced_grids_of_planes = tracer.traced_grids_of_planes_from_grid(
                grid=masked_imaging_7x7.grid
            )
            traced_blurring_grids_of_planes = tracer.traced_grids_of_planes_from_grid(
                grid=masked_imaging_7x7.blurring_grid
            )

            g0_image = g0.profile_image_from_grid(grid=traced_grids_of_planes[0])
            g0_blurring_image = g0.profile_image_from_grid(
                grid=traced_blurring_grids_of_planes[0]
            )

            g0_blurred_image = masked_imaging_7x7.convolver.convolved_image_from_image_and_blurring_image(
                image=g0_image, blurring_image=g0_blurring_image
            )

            g1_image = g1.profile_image_from_grid(grid=traced_grids_of_planes[1])
            g1_blurring_image = g1.profile_image_from_grid(
                grid=traced_blurring_grids_of_planes[1]
            )

            g1_blurred_image = masked_imaging_7x7.convolver.convolved_image_from_image_and_blurring_image(
                image=g1_image, blurring_image=g1_blurring_image
            )

            assert fit.galaxy_model_image_dict[g0] == pytest.approx(
                g0_blurred_image, 1.0e-4
            )
            assert fit.galaxy_model_image_dict[g1] == pytest.approx(
                g1_blurred_image, 1.0e-4
            )
            assert (fit.galaxy_model_image_dict[g2].in_1d == np.zeros(9)).all()

            assert fit.model_image.in_2d == pytest.approx(
                fit.galaxy_model_image_dict[g0].in_2d
                + fit.galaxy_model_image_dict[g1].in_2d,
                1.0e-4,
            )

        def test___all_lens_fit_quantities__including_hyper_methods(
            self, masked_imaging_7x7
        ):

            hyper_image_sky = al.hyper_data.HyperImageSky(sky_scale=1.0)

            hyper_background_noise = al.hyper_data.HyperBackgroundNoise(noise_scale=1.0)

            image = hyper_image_sky.hyper_image_from_image(
                image=masked_imaging_7x7.image
            )

            g0 = al.Galaxy(
                redshift=0.5,
                light_profile=al.lp.EllipticalSersic(intensity=1.0),
                mass_profile=al.mp.SphericalIsothermal(einstein_radius=1.0),
                hyper_galaxy=al.HyperGalaxy(
                    contribution_factor=1.0, noise_factor=1.0, noise_power=1.0
                ),
                hyper_model_image=np.ones(9),
                hyper_galaxy_image=np.ones(9),
                hyper_minimum_value=0.0,
            )
            g1 = al.Galaxy(
                redshift=1.0, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1])

            fit = ImagingFit(
                masked_imaging=masked_imaging_7x7,
                tracer=tracer,
                hyper_image_sky=hyper_image_sky,
                hyper_background_noise=hyper_background_noise,
            )

            hyper_noise_map_background = hyper_background_noise.hyper_noise_map_from_noise_map(
                noise_map=masked_imaging_7x7.noise_map
            )

            hyper_noise = tracer.hyper_noise_map_from_noise_map(
                noise_map=masked_imaging_7x7.noise_map
            )

            hyper_noise_map = hyper_noise_map_background + hyper_noise

            assert hyper_noise_map.in_2d == pytest.approx(fit.noise_map.in_2d)

            model_image = tracer.blurred_profile_image_from_grid_and_convolver(
                grid=masked_imaging_7x7.grid,
                convolver=masked_imaging_7x7.convolver,
                blurring_grid=masked_imaging_7x7.blurring_grid,
            )

            assert model_image.in_2d == pytest.approx(fit.model_image.in_2d)

            residual_map = al.util.fit.residual_map_from_data_and_model_data(
                data=image, model_data=model_image
            )

            assert residual_map.in_2d == pytest.approx(fit.residual_map.in_2d)

            normalized_residual_map = al.util.fit.normalized_residual_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=hyper_noise_map
            )

            assert normalized_residual_map.in_2d == pytest.approx(
                fit.normalized_residual_map.in_2d
            )

            chi_squared_map = al.util.fit.chi_squared_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=hyper_noise_map
            )

            assert chi_squared_map.in_2d == pytest.approx(fit.chi_squared_map.in_2d)

            chi_squared = al.util.fit.chi_squared_from_chi_squared_map(
                chi_squared_map=chi_squared_map
            )

            noise_normalization = al.util.fit.noise_normalization_from_noise_map(
                noise_map=hyper_noise_map
            )

            likelihood = al.util.fit.likelihood_from_chi_squared_and_noise_normalization(
                chi_squared=chi_squared, noise_normalization=noise_normalization
            )

            assert likelihood == pytest.approx(fit.likelihood, 1e-4)
            assert likelihood == fit.figure_of_merit

        def test___blurred_and_model_images_of_planes_and_unmasked_blurred_profile_image_properties(
            self, masked_imaging_7x7
        ):

            g0 = al.Galaxy(
                redshift=0.5,
                light_profile=al.lp.EllipticalSersic(intensity=1.0),
                mass_profile=al.mp.SphericalIsothermal(einstein_radius=1.0),
            )

            g1 = al.Galaxy(
                redshift=1.0, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            blurred_profile_images_of_planes = tracer.blurred_profile_images_of_planes_from_grid_and_convolver(
                grid=masked_imaging_7x7.grid,
                convolver=masked_imaging_7x7.convolver,
                blurring_grid=masked_imaging_7x7.blurring_grid,
            )

            assert blurred_profile_images_of_planes[0].in_2d == pytest.approx(
                fit.model_images_of_planes[0].in_2d, 1.0e-4
            )

            assert blurred_profile_images_of_planes[1].in_2d == pytest.approx(
                fit.model_images_of_planes[1].in_2d, 1.0e-4
            )

            unmasked_blurred_profile_image = tracer.unmasked_blurred_profile_image_from_grid_and_psf(
                grid=masked_imaging_7x7.grid, psf=masked_imaging_7x7.psf
            )

            assert (
                unmasked_blurred_profile_image == fit.unmasked_blurred_profile_image
            ).all()

            unmasked_blurred_profile_image_of_planes = tracer.unmasked_blurred_profile_image_of_planes_from_grid_and_psf(
                grid=masked_imaging_7x7.grid, psf=masked_imaging_7x7.psf
            )

            assert (
                unmasked_blurred_profile_image_of_planes[0]
                == fit.unmasked_blurred_profile_image_of_planes[0]
            ).all()
            assert (
                unmasked_blurred_profile_image_of_planes[1]
                == fit.unmasked_blurred_profile_image_of_planes[1]
            ).all()

            unmasked_blurred_profile_image_of_galaxies = tracer.unmasked_blurred_profile_image_of_planes_and_galaxies_from_grid_and_psf(
                grid=masked_imaging_7x7.grid, psf=masked_imaging_7x7.psf
            )

            assert (
                unmasked_blurred_profile_image_of_galaxies[0][0]
                == fit.unmasked_blurred_profile_image_of_planes_and_galaxies[0][0]
            ).all()
            assert (
                unmasked_blurred_profile_image_of_galaxies[1][0]
                == fit.unmasked_blurred_profile_image_of_planes_and_galaxies[1][0]
            ).all()

    class TestCompareToManualInversionOnly:
        def test___all_lens_fit_quantities__no_hyper_methods(self, masked_imaging_7x7):

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)

            g0 = al.Galaxy(redshift=0.5, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[al.Galaxy(redshift=0.5), g0])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_imaging_7x7.grid, sparse_grid=None
            )
            inversion = inversions.InversionImaging.from_data_mapper_and_regularization(
                mapper=mapper,
                regularization=reg,
                image=masked_imaging_7x7.image,
                noise_map=masked_imaging_7x7.noise_map,
                convolver=masked_imaging_7x7.convolver,
            )

            assert inversion.mapped_reconstructed_image.in_2d == pytest.approx(
                fit.model_image.in_2d, 1.0e-4
            )

            residual_map = al.util.fit.residual_map_from_data_and_model_data(
                data=masked_imaging_7x7.image,
                model_data=inversion.mapped_reconstructed_image,
            )

            assert residual_map.in_2d == pytest.approx(fit.residual_map.in_2d, 1.0e-4)

            normalized_residual_map = al.util.fit.normalized_residual_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_imaging_7x7.noise_map
            )

            assert normalized_residual_map.in_2d == pytest.approx(
                fit.normalized_residual_map.in_2d, 1.0e-4
            )

            chi_squared_map = al.util.fit.chi_squared_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_imaging_7x7.noise_map
            )

            assert chi_squared_map.in_2d == pytest.approx(
                fit.chi_squared_map.in_2d, 1.0e-4
            )

            chi_squared = al.util.fit.chi_squared_from_chi_squared_map(
                chi_squared_map=chi_squared_map
            )

            noise_normalization = al.util.fit.noise_normalization_from_noise_map(
                noise_map=masked_imaging_7x7.noise_map
            )

            likelihood = al.util.fit.likelihood_from_chi_squared_and_noise_normalization(
                chi_squared=chi_squared, noise_normalization=noise_normalization
            )

            assert likelihood == pytest.approx(fit.likelihood, 1e-4)

            likelihood_with_regularization = al.util.fit.likelihood_with_regularization_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                noise_normalization=noise_normalization,
            )

            assert likelihood_with_regularization == pytest.approx(
                fit.likelihood_with_regularization, 1e-4
            )

            evidence = al.util.fit.evidence_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                log_curvature_regularization_term=inversion.log_det_curvature_reg_matrix_term,
                log_regularization_term=inversion.log_det_regularization_matrix_term,
                noise_normalization=noise_normalization,
            )

            assert evidence == fit.evidence
            assert evidence == fit.figure_of_merit

        def test___lens_fit_galaxy_model_image_dict__has_inversion_mapped_reconstructed_image(
            self, masked_imaging_7x7
        ):
            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)

            g0 = al.Galaxy(redshift=0.5)
            g1 = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_imaging_7x7.grid, sparse_grid=None
            )

            inversion = inversions.InversionImaging.from_data_mapper_and_regularization(
                mapper=mapper,
                regularization=reg,
                image=masked_imaging_7x7.image,
                noise_map=masked_imaging_7x7.noise_map,
                convolver=masked_imaging_7x7.convolver,
            )

            assert (fit.galaxy_model_image_dict[g0] == np.zeros(9)).all()

            assert fit.galaxy_model_image_dict[g1].in_2d == pytest.approx(
                inversion.mapped_reconstructed_image.in_2d, 1.0e-4
            )

            assert fit.model_image.in_2d == pytest.approx(
                fit.galaxy_model_image_dict[g1].in_2d, 1.0e-4
            )

        def test___all_lens_fit_quantities__include_hyper_methods(
            self, masked_imaging_7x7
        ):

            hyper_image_sky = al.hyper_data.HyperImageSky(sky_scale=1.0)

            hyper_background_noise = al.hyper_data.HyperBackgroundNoise(noise_scale=1.0)

            image = hyper_image_sky.hyper_image_from_image(
                image=masked_imaging_7x7.image
            )

            hyper_noise_map_background = hyper_background_noise.hyper_noise_map_from_noise_map(
                noise_map=masked_imaging_7x7.noise_map
            )

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)

            g0 = al.Galaxy(
                redshift=0.5,
                pixelization=pix,
                regularization=reg,
                hyper_galaxy=al.HyperGalaxy(
                    contribution_factor=1.0, noise_factor=1.0, noise_power=1.0
                ),
                hyper_model_image=np.ones(9),
                hyper_galaxy_image=np.ones(9),
                hyper_minimum_value=0.0,
            )

            tracer = al.Tracer.from_galaxies(galaxies=[al.Galaxy(redshift=0.5), g0])

            fit = ImagingFit(
                masked_imaging=masked_imaging_7x7,
                tracer=tracer,
                hyper_image_sky=hyper_image_sky,
                hyper_background_noise=hyper_background_noise,
            )

            hyper_noise = tracer.hyper_noise_map_from_noise_map(
                noise_map=masked_imaging_7x7.noise_map
            )
            hyper_noise_map = hyper_noise_map_background + hyper_noise

            assert hyper_noise_map.in_2d == pytest.approx(fit.noise_map.in_2d)

            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_imaging_7x7.grid, inversion_uses_border=False
            )
            inversion = inversions.InversionImaging.from_data_mapper_and_regularization(
                mapper=mapper,
                regularization=reg,
                image=image,
                noise_map=hyper_noise_map,
                convolver=masked_imaging_7x7.convolver,
            )

            assert inversion.mapped_reconstructed_image.in_2d == pytest.approx(
                fit.model_image.in_2d, 1.0e-4
            )

            residual_map = al.util.fit.residual_map_from_data_and_model_data(
                data=image, model_data=inversion.mapped_reconstructed_image
            )

            assert residual_map.in_2d == pytest.approx(fit.residual_map.in_2d)

            normalized_residual_map = al.util.fit.normalized_residual_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=hyper_noise_map
            )

            assert normalized_residual_map.in_2d == pytest.approx(
                fit.normalized_residual_map.in_2d
            )

            chi_squared_map = al.util.fit.chi_squared_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=hyper_noise_map
            )

            assert chi_squared_map.in_2d == pytest.approx(fit.chi_squared_map.in_2d)

            chi_squared = al.util.fit.chi_squared_from_chi_squared_map(
                chi_squared_map=chi_squared_map
            )

            noise_normalization = al.util.fit.noise_normalization_from_noise_map(
                noise_map=hyper_noise_map
            )

            likelihood = al.util.fit.likelihood_from_chi_squared_and_noise_normalization(
                chi_squared=chi_squared, noise_normalization=noise_normalization
            )

            assert likelihood == pytest.approx(fit.likelihood, 1e-4)

            likelihood_with_regularization = al.util.fit.likelihood_with_regularization_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                noise_normalization=noise_normalization,
            )

            assert likelihood_with_regularization == pytest.approx(
                fit.likelihood_with_regularization, 1e-4
            )

            evidence = al.util.fit.evidence_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                log_curvature_regularization_term=inversion.log_det_curvature_reg_matrix_term,
                log_regularization_term=inversion.log_det_regularization_matrix_term,
                noise_normalization=noise_normalization,
            )

            assert evidence == fit.evidence
            assert evidence == fit.figure_of_merit

        def test___blurred_and_model_images_of_planes_and_unmasked_blurred_profile_image_properties(
            self, masked_imaging_7x7
        ):

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)

            g0 = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[al.Galaxy(redshift=0.5), g0])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_imaging_7x7.grid, inversion_uses_border=False
            )

            inversion = inversions.InversionImaging.from_data_mapper_and_regularization(
                mapper=mapper,
                regularization=reg,
                image=masked_imaging_7x7.image,
                noise_map=masked_imaging_7x7.noise_map,
                convolver=masked_imaging_7x7.convolver,
            )

            assert (fit.model_images_of_planes[0].in_2d == np.zeros((7, 7))).all()
            assert inversion.mapped_reconstructed_image.in_2d == pytest.approx(
                fit.model_images_of_planes[1].in_2d, 1.0e-4
            )

    class TestCompareToManualProfilesAndInversion:
        def test___all_lens_fit_quantities__no_hyper_methods(self, masked_imaging_7x7):
            galaxy_light = al.Galaxy(
                redshift=0.5, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)
            galaxy_pix = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[galaxy_light, galaxy_pix])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            blurred_profile_image = tracer.blurred_profile_image_from_grid_and_convolver(
                grid=masked_imaging_7x7.grid,
                convolver=masked_imaging_7x7.convolver,
                blurring_grid=masked_imaging_7x7.blurring_grid,
            )

            assert blurred_profile_image.in_2d == pytest.approx(
                fit.blurred_profile_image.in_2d
            )

            profile_subtracted_image = masked_imaging_7x7.image - blurred_profile_image

            assert profile_subtracted_image.in_2d == pytest.approx(
                fit.profile_subtracted_image.in_2d
            )

            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_imaging_7x7.grid, inversion_uses_border=False
            )

            inversion = inversions.InversionImaging.from_data_mapper_and_regularization(
                image=profile_subtracted_image,
                noise_map=masked_imaging_7x7.noise_map,
                convolver=masked_imaging_7x7.convolver,
                mapper=mapper,
                regularization=reg,
            )

            model_image = blurred_profile_image + inversion.mapped_reconstructed_image

            assert model_image.in_2d == pytest.approx(fit.model_image.in_2d)

            residual_map = al.util.fit.residual_map_from_data_and_model_data(
                data=masked_imaging_7x7.image, model_data=model_image
            )

            assert residual_map.in_2d == pytest.approx(fit.residual_map.in_2d)

            normalized_residual_map = al.util.fit.normalized_residual_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_imaging_7x7.noise_map
            )

            assert normalized_residual_map.in_2d == pytest.approx(
                fit.normalized_residual_map.in_2d
            )

            chi_squared_map = al.util.fit.chi_squared_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_imaging_7x7.noise_map
            )

            assert chi_squared_map.in_2d == pytest.approx(fit.chi_squared_map.in_2d)

            chi_squared = al.util.fit.chi_squared_from_chi_squared_map(
                chi_squared_map=chi_squared_map
            )

            noise_normalization = al.util.fit.noise_normalization_from_noise_map(
                noise_map=masked_imaging_7x7.noise_map
            )

            likelihood = al.util.fit.likelihood_from_chi_squared_and_noise_normalization(
                chi_squared=chi_squared, noise_normalization=noise_normalization
            )

            assert likelihood == pytest.approx(fit.likelihood, 1e-4)

            likelihood_with_regularization = al.util.fit.likelihood_with_regularization_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                noise_normalization=noise_normalization,
            )

            assert likelihood_with_regularization == pytest.approx(
                fit.likelihood_with_regularization, 1e-4
            )

            evidence = al.util.fit.evidence_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                log_curvature_regularization_term=inversion.log_det_curvature_reg_matrix_term,
                log_regularization_term=inversion.log_det_regularization_matrix_term,
                noise_normalization=noise_normalization,
            )

            assert evidence == fit.evidence
            assert evidence == fit.figure_of_merit

        def test___lens_fit_galaxy_model_image_dict__has_blurred_profile_images_and_inversion_mapped_reconstructed_image(
            self, masked_imaging_7x7
        ):

            g0 = al.Galaxy(
                redshift=0.5, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )
            g1 = al.Galaxy(
                redshift=0.5, light_profile=al.lp.EllipticalSersic(intensity=2.0)
            )
            g2 = al.Galaxy(redshift=0.5)

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)
            galaxy_pix = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2, galaxy_pix])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            traced_grids = tracer.traced_grids_of_planes_from_grid(
                grid=masked_imaging_7x7.grid
            )
            traced_blurring_grids = tracer.traced_grids_of_planes_from_grid(
                grid=masked_imaging_7x7.blurring_grid
            )

            g0_image = g0.profile_image_from_grid(grid=traced_grids[0])
            g0_blurring_image = g0.profile_image_from_grid(
                grid=traced_blurring_grids[0]
            )

            g0_blurred_image = masked_imaging_7x7.convolver.convolved_image_from_image_and_blurring_image(
                image=g0_image, blurring_image=g0_blurring_image
            )

            g1_image = g1.profile_image_from_grid(grid=traced_grids[1])
            g1_blurring_image = g1.profile_image_from_grid(
                grid=traced_blurring_grids[1]
            )

            g1_blurred_image = masked_imaging_7x7.convolver.convolved_image_from_image_and_blurring_image(
                image=g1_image, blurring_image=g1_blurring_image
            )

            blurred_profile_image = g0_blurred_image + g1_blurred_image

            profile_subtracted_image = masked_imaging_7x7.image - blurred_profile_image
            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_imaging_7x7.grid, inversion_uses_border=False
            )

            inversion = inversions.InversionImaging.from_data_mapper_and_regularization(
                image=profile_subtracted_image,
                noise_map=masked_imaging_7x7.noise_map,
                convolver=masked_imaging_7x7.convolver,
                mapper=mapper,
                regularization=reg,
            )

            assert (fit.galaxy_model_image_dict[g2] == np.zeros(9)).all()

            assert fit.galaxy_model_image_dict[g0].in_2d == pytest.approx(
                g0_blurred_image.in_2d, 1.0e-4
            )
            assert fit.galaxy_model_image_dict[g1].in_2d == pytest.approx(
                g1_blurred_image.in_2d, 1.0e-4
            )
            assert fit.galaxy_model_image_dict[galaxy_pix].in_2d == pytest.approx(
                inversion.mapped_reconstructed_image.in_2d, 1.0e-4
            )

            assert fit.model_image.in_2d == pytest.approx(
                fit.galaxy_model_image_dict[g0].in_2d
                + fit.galaxy_model_image_dict[g1].in_2d
                + inversion.mapped_reconstructed_image.in_2d,
                1.0e-4,
            )

        def test___all_lens_fit_quantities__include_hyper_methods(
            self, masked_imaging_7x7
        ):

            hyper_image_sky = al.hyper_data.HyperImageSky(sky_scale=1.0)

            hyper_background_noise = al.hyper_data.HyperBackgroundNoise(noise_scale=1.0)

            image = hyper_image_sky.hyper_image_from_image(
                image=masked_imaging_7x7.image
            )

            hyper_noise_map_background = hyper_background_noise.hyper_noise_map_from_noise_map(
                noise_map=masked_imaging_7x7.noise_map
            )

            galaxy_light = al.Galaxy(
                redshift=0.5,
                light_profile=al.lp.EllipticalSersic(intensity=1.0),
                hyper_galaxy=al.HyperGalaxy(
                    contribution_factor=1.0, noise_factor=1.0, noise_power=1.0
                ),
                hyper_model_image=al.array.ones(shape_2d=(3, 3)),
                hyper_galaxy_image=al.array.ones(shape_2d=(3, 3)),
                hyper_minimum_value=0.0,
            )

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)
            galaxy_pix = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[galaxy_light, galaxy_pix])

            fit = ImagingFit(
                masked_imaging=masked_imaging_7x7,
                tracer=tracer,
                hyper_image_sky=hyper_image_sky,
                hyper_background_noise=hyper_background_noise,
            )

            hyper_noise = tracer.hyper_noise_map_from_noise_map(
                noise_map=masked_imaging_7x7.noise_map
            )
            hyper_noise_map = hyper_noise_map_background + hyper_noise

            assert hyper_noise_map.in_2d == pytest.approx(fit.noise_map.in_2d, 1.0e-4)

            blurred_profile_image = tracer.blurred_profile_image_from_grid_and_convolver(
                grid=masked_imaging_7x7.grid,
                convolver=masked_imaging_7x7.convolver,
                blurring_grid=masked_imaging_7x7.blurring_grid,
            )

            assert blurred_profile_image.in_2d == pytest.approx(
                fit.blurred_profile_image.in_2d
            )

            profile_subtracted_image = image - blurred_profile_image

            assert profile_subtracted_image.in_2d == pytest.approx(
                fit.profile_subtracted_image.in_2d
            )

            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_imaging_7x7.grid, inversion_uses_border=False
            )

            inversion = inversions.InversionImaging.from_data_mapper_and_regularization(
                image=profile_subtracted_image,
                noise_map=hyper_noise_map,
                convolver=masked_imaging_7x7.convolver,
                mapper=mapper,
                regularization=reg,
            )

            model_image = blurred_profile_image + inversion.mapped_reconstructed_image

            assert model_image.in_2d == pytest.approx(fit.model_image.in_2d, 1.0e-4)

            residual_map = al.util.fit.residual_map_from_data_and_model_data(
                data=image, model_data=model_image
            )

            assert residual_map.in_2d == pytest.approx(fit.residual_map.in_2d, 1.0e-4)

            normalized_residual_map = al.util.fit.normalized_residual_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=hyper_noise_map
            )

            assert normalized_residual_map.in_2d == pytest.approx(
                fit.normalized_residual_map.in_2d, 1.0e-4
            )

            chi_squared_map = al.util.fit.chi_squared_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=hyper_noise_map
            )

            assert chi_squared_map.in_2d == pytest.approx(
                fit.chi_squared_map.in_2d, 1.0e-4
            )

            chi_squared = al.util.fit.chi_squared_from_chi_squared_map(
                chi_squared_map=chi_squared_map
            )

            noise_normalization = al.util.fit.noise_normalization_from_noise_map(
                noise_map=hyper_noise_map
            )

            likelihood = al.util.fit.likelihood_from_chi_squared_and_noise_normalization(
                chi_squared=chi_squared, noise_normalization=noise_normalization
            )

            assert likelihood == pytest.approx(fit.likelihood, 1e-4)

            likelihood_with_regularization = al.util.fit.likelihood_with_regularization_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                noise_normalization=noise_normalization,
            )

            assert likelihood_with_regularization == pytest.approx(
                fit.likelihood_with_regularization, 1e-4
            )

            evidence = al.util.fit.evidence_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                log_curvature_regularization_term=inversion.log_det_curvature_reg_matrix_term,
                log_regularization_term=inversion.log_det_regularization_matrix_term,
                noise_normalization=noise_normalization,
            )

            assert evidence == fit.evidence
            assert evidence == fit.figure_of_merit

        def test___blurred_and_model_images_of_planes_and_unmasked_blurred_profile_image_properties(
            self, masked_imaging_7x7
        ):
            galaxy_light = al.Galaxy(
                redshift=0.5, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)
            galaxy_pix = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[galaxy_light, galaxy_pix])

            fit = ImagingFit(masked_imaging=masked_imaging_7x7, tracer=tracer)

            blurred_profile_image = tracer.blurred_profile_image_from_grid_and_convolver(
                grid=masked_imaging_7x7.grid,
                convolver=masked_imaging_7x7.convolver,
                blurring_grid=masked_imaging_7x7.blurring_grid,
            )

            profile_subtracted_image = masked_imaging_7x7.image - blurred_profile_image

            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_imaging_7x7.grid, inversion_uses_border=False
            )

            inversion = inversions.InversionImaging.from_data_mapper_and_regularization(
                image=profile_subtracted_image,
                noise_map=masked_imaging_7x7.noise_map,
                convolver=masked_imaging_7x7.convolver,
                mapper=mapper,
                regularization=reg,
            )

            assert blurred_profile_image.in_2d == pytest.approx(
                fit.model_images_of_planes[0].in_2d, 1.0e-4
            )
            assert inversion.mapped_reconstructed_image.in_2d == pytest.approx(
                fit.model_images_of_planes[1].in_2d, 1.0e-4
            )


class TestInterferometerFit:
    class TestFitProperties:
        def test__total_inversions(self, masked_interferometer_7):
            g0 = al.Galaxy(redshift=0.5)

            g1 = al.Galaxy(redshift=1.0)

            g2 = al.Galaxy(redshift=2.0)

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            assert fit.total_inversions == 0

            g2 = al.Galaxy(
                redshift=2.0,
                pixelization=al.pix.Rectangular(),
                regularization=al.reg.Constant(),
            )

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            assert fit.total_inversions == 1

            g0 = al.Galaxy(
                redshift=0.5,
                pixelization=al.pix.Rectangular(),
                regularization=al.reg.Constant(),
            )

            g1 = al.Galaxy(
                redshift=1.0,
                pixelization=al.pix.Rectangular(),
                regularization=al.reg.Constant(),
            )

            g2 = al.Galaxy(
                redshift=2.0,
                pixelization=al.pix.Rectangular(),
                regularization=al.reg.Constant(),
            )

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            assert fit.total_inversions == 3

    class TestLikelihood:
        def test__1x2_image__1x2_visibilities__simple_fourier_transform(self):
            # The image plane image generated by the galaxy is [1.0, 1.0]

            # Thus the chi squared is 4.0**2.0 + 3.0**2.0 = 25.0

            uv_wavelengths = np.array([[0.0, 0.0]])

            interferometer = al.interferometer.manual(
                visibilities=al.visibilities.full(fill_value=5.0, shape_1d=(1,)),
                noise_map=al.visibilities.ones(shape_1d=(1,)),
                uv_wavelengths=uv_wavelengths,
                primary_beam=None,
            )

            interferometer.visibilities[0, 1] = 4.0

            visibilities_mask = np.full(fill_value=False, shape=(1, 2))

            real_space_mask = al.mask.manual(
                mask_2d=np.array(
                    [
                        [True, True, True, True],
                        [True, False, False, True],
                        [True, True, True, True],
                    ]
                ),
                pixel_scales=1.0,
                sub_size=1,
            )

            masked_interferometer = al.masked_interferometer(
                interferometer=interferometer,
                visibilities_mask=visibilities_mask,
                real_space_mask=real_space_mask,
            )

            # Setup as a ray trace instance, using a light profile for the lens

            g0 = al.Galaxy(
                redshift=0.5, light_profile=MockLightProfile(value=1.0, size=2)
            )
            tracer = al.Tracer.from_galaxies(galaxies=[g0])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer, tracer=tracer
            )

            assert (fit.visibilities_mask == np.array([False, False])).all()

            assert (fit.visibilities.in_1d == np.array([[5.0, 4.0]])).all()
            assert (fit.noise_map.in_1d == np.array([[1.0, 1.0]])).all()
            assert (fit.model_visibilities.in_1d == np.array([2.0, 0.0])).all()
            assert (fit.residual_map.in_1d == np.array([3.0, 4.0])).all()
            assert (fit.normalized_residual_map.in_1d == np.array([3.0, 4.0])).all()
            assert (fit.chi_squared_map.in_1d == np.array([9.0, 16.0])).all()

            assert fit.chi_squared == 25.0
            assert fit.reduced_chi_squared == 25.0 / 2.0
            assert fit.noise_normalization == (2.0 * np.log(2 * np.pi * 1.0 ** 2.0))
            assert fit.likelihood == -0.5 * (
                25.0 + 2.0 * np.log(2 * np.pi * 1.0 ** 2.0)
            )

        def test__3x2_image__2x2_visibilities__use_transformer_for_likelihood(self):

            uv_wavelengths = np.array([[1.0, 0.0], [1.0, 1.0], [2.0, 2.0]])

            interferometer = al.interferometer.manual(
                visibilities=al.visibilities.full(fill_value=5.0, shape_1d=(3,)),
                noise_map=al.visibilities.full(fill_value=2.0, shape_1d=(3,)),
                uv_wavelengths=uv_wavelengths,
                primary_beam=None,
            )

            transformer = trans.Transformer(
                uv_wavelengths=uv_wavelengths,
                grid_radians=al.grid.manual_2d(
                    [[[0.0, -1.0], [0.0, 1.0], [1.0, 1.0]]], pixel_scales=(1.0, 1.0)
                ),
            )

            visibilities_mask = np.full(fill_value=False, shape=(3, 2))

            real_space_mask = al.mask.manual(
                mask_2d=np.array(
                    [
                        [True, True, True, True, True],
                        [True, False, False, False, True],
                        [True, True, True, True, True],
                    ]
                ),
                pixel_scales=1.0,
                sub_size=1,
            )

            masked_interferometer = al.masked_interferometer(
                interferometer=interferometer,
                visibilities_mask=visibilities_mask,
                real_space_mask=real_space_mask,
            )

            # Setup as a ray trace instance, using a light profile for the lens

            g0 = al.Galaxy(
                redshift=0.5, light_profile=al.lp.EllipticalSersic(intensity=0.001)
            )

            profile_image = g0.profile_image_from_grid(grid=masked_interferometer.grid)
            model_visibilities_manual = transformer.visibilities_from_image(
                image=profile_image
            )

            tracer = al.Tracer.from_galaxies(galaxies=[g0])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer, tracer=tracer
            )

            assert (fit.visibilities_mask == np.array([False, False])).all()

            assert (
                fit.visibilities.in_1d
                == np.array([[[5.0, 5.0], [5.0, 5.0], [5.0, 5.0]]])
            ).all()
            assert (
                fit.noise_map.in_1d == np.array([[[2.0, 2.0], [2.0, 2.0], [2.0, 2.0]]])
            ).all()

            assert fit.model_visibilities.in_1d == pytest.approx(
                model_visibilities_manual, 1.0e-4
            )

            # moddel visibilities are all [1.94805, 0.0]

            assert fit.residual_map.in_1d == pytest.approx(
                np.array([[3.0519, 5.0], [3.0519, 5.0], [3.0519, 5.0]]), 1.0e-4
            )

            assert fit.normalized_residual_map.in_1d == pytest.approx(
                np.array(
                    [
                        [3.0519 / 2.0, 5.0 / 2.0],
                        [3.0519 / 2.0, 5.0 / 2.0],
                        [3.0519 / 2.0, 5.0 / 2.0],
                    ]
                ),
                1.0e-4,
            )

            assert fit.chi_squared_map.in_1d == pytest.approx(
                np.array(
                    [
                        [(3.0519 / 2.0) ** 2.0, (5.0 / 2.0) ** 2.0],
                        [(3.0519 / 2.0) ** 2.0, (5.0 / 2.0) ** 2.0],
                        [(3.0519 / 2.0) ** 2.0, (5.0 / 2.0) ** 2.0],
                    ]
                ),
                1.0e-4,
            )

            assert fit.chi_squared == pytest.approx(25.73579, 1.0e-4)
            assert fit.reduced_chi_squared == pytest.approx(25.73579 / 6.0)
            assert fit.noise_normalization == pytest.approx(
                (6.0 * np.log(2 * np.pi * 2.0 ** 2.0)), 1.0e-4
            )
            assert fit.likelihood == pytest.approx(
                -0.5 * (25.73579 + 6.0 * np.log(2 * np.pi * 2.0 ** 2.0)), 1.0e-4
            )

        def test__hyper_background_changes_background_sky__reflected_in_likelihood(
            self
        ):

            uv_wavelengths = np.array([[1.0, 0.0], [1.0, 1.0], [2.0, 2.0]])

            interferometer = al.interferometer.manual(
                visibilities=al.visibilities.full(fill_value=5.0, shape_1d=(3,)),
                noise_map=al.visibilities.full(fill_value=2.0, shape_1d=(3,)),
                uv_wavelengths=uv_wavelengths,
                primary_beam=None,
            )

            visibilities_mask = np.full(fill_value=False, shape=(1, 2))

            real_space_mask = al.mask.manual(
                mask_2d=np.array(
                    [
                        [True, True, True, True, True],
                        [True, False, False, False, True],
                        [True, True, True, True, True],
                    ]
                ),
                pixel_scales=1.0,
                sub_size=1,
            )

            masked_interferometer = al.masked_interferometer(
                interferometer=interferometer,
                visibilities_mask=visibilities_mask,
                real_space_mask=real_space_mask,
            )

            # Setup as a ray trace instance, using a light profile for the lens

            g0 = al.Galaxy(
                redshift=0.5, light_profile=MockLightProfile(value=1.0, size=2)
            )
            tracer = al.Tracer.from_galaxies(galaxies=[g0])

            hyper_background_noise = al.hyper_data.HyperBackgroundNoise(noise_scale=1.0)

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer,
                tracer=tracer,
                hyper_background_noise=hyper_background_noise,
            )

            assert (
                fit.visibilities.in_1d == np.full(fill_value=5.0, shape=(3, 2))
            ).all()

            assert (fit.noise_map.in_1d == np.full(fill_value=3.0, shape=(3, 2))).all()

    class TestCompareToManualProfilesOnly:
        def test___all_lens_fit_quantities__no_hyper_methods(
            self, masked_interferometer_7
        ):
            g0 = al.Galaxy(
                redshift=0.5,
                light_profile=al.lp.EllipticalSersic(intensity=1.0),
                mass_profile=al.mp.SphericalIsothermal(einstein_radius=1.0),
            )

            g1 = al.Galaxy(
                redshift=1.0, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            assert masked_interferometer_7.noise_map == pytest.approx(fit.noise_map)

            model_visibilities = tracer.profile_visibilities_from_grid_and_transformer(
                grid=masked_interferometer_7.grid,
                transformer=masked_interferometer_7.transformer,
            )

            assert model_visibilities == pytest.approx(fit.model_visibilities, 1e-4)

            residual_map = al.util.fit.residual_map_from_data_and_model_data(
                data=masked_interferometer_7.visibilities, model_data=model_visibilities
            )

            assert residual_map == pytest.approx(fit.residual_map, 1e-4)

            normalized_residual_map = al.util.fit.normalized_residual_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_interferometer_7.noise_map
            )

            assert normalized_residual_map == pytest.approx(
                fit.normalized_residual_map, 1e-4
            )

            chi_squared_map = al.util.fit.chi_squared_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_interferometer_7.noise_map
            )

            assert chi_squared_map == pytest.approx(fit.chi_squared_map, 1e-4)

            chi_squared = al.util.fit.chi_squared_from_chi_squared_map(
                chi_squared_map=fit.chi_squared_map
            )

            noise_normalization = al.util.fit.noise_normalization_from_noise_map(
                noise_map=masked_interferometer_7.noise_map
            )

            likelihood = al.util.fit.likelihood_from_chi_squared_and_noise_normalization(
                chi_squared=chi_squared, noise_normalization=noise_normalization
            )

            assert likelihood == pytest.approx(fit.likelihood, 1e-4)
            assert likelihood == fit.figure_of_merit

        def test___lens_fit_galaxy_model_image_dict__corresponds_to_profile_galaxy_images(
            self, masked_interferometer_7
        ):
            g0 = al.Galaxy(
                redshift=0.5,
                light_profile=al.lp.EllipticalSersic(intensity=1.0),
                mass_profile=al.mp.SphericalIsothermal(einstein_radius=1.0),
            )
            g1 = al.Galaxy(
                redshift=1.0, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )
            g2 = al.Galaxy(redshift=1.0)

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            traced_grids_of_planes = tracer.traced_grids_of_planes_from_grid(
                grid=masked_interferometer_7.grid
            )

            g0_profile_image = g0.profile_image_from_grid(
                grid=traced_grids_of_planes[0]
            )

            g1_profile_image = g1.profile_image_from_grid(
                grid=traced_grids_of_planes[1]
            )

            assert fit.galaxy_model_image_dict[g0].in_1d == pytest.approx(
                g0_profile_image, 1.0e-4
            )
            assert fit.galaxy_model_image_dict[g1].in_1d == pytest.approx(
                g1_profile_image, 1.0e-4
            )

        def test___lens_fit_galaxy_visibilities_dict__corresponds_to_galaxy_visibilities(
            self, masked_interferometer_7
        ):
            g0 = al.Galaxy(
                redshift=0.5,
                light_profile=al.lp.EllipticalSersic(intensity=1.0),
                mass_profile=al.mp.SphericalIsothermal(einstein_radius=1.0),
            )
            g1 = al.Galaxy(
                redshift=1.0, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )
            g2 = al.Galaxy(redshift=1.0)

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            traced_grids_of_planes = tracer.traced_grids_of_planes_from_grid(
                grid=masked_interferometer_7.grid
            )

            g0_profile_visibilities = g0.profile_visibilities_from_grid_and_transformer(
                grid=traced_grids_of_planes[0],
                transformer=masked_interferometer_7.transformer,
            )

            g1_profile_visibilities = g1.profile_visibilities_from_grid_and_transformer(
                grid=traced_grids_of_planes[1],
                transformer=masked_interferometer_7.transformer,
            )

            assert fit.galaxy_model_visibilities_dict[g0].in_1d == pytest.approx(
                g0_profile_visibilities, 1.0e-4
            )
            assert fit.galaxy_model_visibilities_dict[g1].in_1d == pytest.approx(
                g1_profile_visibilities, 1.0e-4
            )
            assert (
                fit.galaxy_model_visibilities_dict[g2].in_1d == np.zeros((7, 2))
            ).all()

            assert fit.model_visibilities.in_1d == pytest.approx(
                fit.galaxy_model_visibilities_dict[g0].in_1d
                + fit.galaxy_model_visibilities_dict[g1].in_1d,
                1.0e-4,
            )

        def test___all_lens_fit_quantities__hyper_background_noise(
            self, masked_interferometer_7
        ):

            hyper_background_noise = al.hyper_data.HyperBackgroundNoise(noise_scale=1.0)

            hyper_noise_map = hyper_background_noise.hyper_noise_map_from_noise_map(
                noise_map=masked_interferometer_7.noise_map
            )

            g0 = al.Galaxy(
                redshift=0.5,
                light_profile=al.lp.EllipticalSersic(intensity=1.0),
                mass_profile=al.mp.SphericalIsothermal(einstein_radius=1.0),
            )

            g1 = al.Galaxy(
                redshift=1.0, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7,
                tracer=tracer,
                hyper_background_noise=hyper_background_noise,
            )

            assert hyper_noise_map.in_1d == pytest.approx(fit.noise_map.in_1d)

    class TestCompareToManualInversionOnly:
        def test___all_lens_fit_quantities__no_hyper_methods(
            self, masked_interferometer_7
        ):

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=0.01)

            g0 = al.Galaxy(redshift=0.5, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[al.Galaxy(redshift=0.5), g0])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_interferometer_7.grid, sparse_grid=None
            )

            inversion = inversions.InversionInterferometer.from_data_mapper_and_regularization(
                mapper=mapper,
                regularization=reg,
                visibilities=masked_interferometer_7.visibilities,
                noise_map=masked_interferometer_7.noise_map,
                transformer=masked_interferometer_7.transformer,
            )

            assert inversion.mapped_reconstructed_visibilities == pytest.approx(
                fit.model_visibilities, 1.0e-4
            )

            residual_map = al.util.fit.residual_map_from_data_and_model_data(
                data=masked_interferometer_7.visibilities,
                model_data=inversion.mapped_reconstructed_visibilities,
            )

            assert residual_map.in_1d == pytest.approx(fit.residual_map.in_1d, 1.0e-4)

            normalized_residual_map = al.util.fit.normalized_residual_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_interferometer_7.noise_map
            )

            assert normalized_residual_map.in_1d == pytest.approx(
                fit.normalized_residual_map.in_1d, 1.0e-4
            )

            chi_squared_map = al.util.fit.chi_squared_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_interferometer_7.noise_map
            )

            assert chi_squared_map.in_1d == pytest.approx(
                fit.chi_squared_map.in_1d, 1.0e-4
            )

            chi_squared = al.util.fit.chi_squared_from_chi_squared_map(
                chi_squared_map=chi_squared_map
            )

            noise_normalization = al.util.fit.noise_normalization_from_noise_map(
                noise_map=masked_interferometer_7.noise_map
            )

            likelihood = al.util.fit.likelihood_from_chi_squared_and_noise_normalization(
                chi_squared=chi_squared, noise_normalization=noise_normalization
            )

            assert likelihood == pytest.approx(fit.likelihood, 1e-4)

            likelihood_with_regularization = al.util.fit.likelihood_with_regularization_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                noise_normalization=noise_normalization,
            )

            assert likelihood_with_regularization == pytest.approx(
                fit.likelihood_with_regularization, 1e-4
            )

            evidence = al.util.fit.evidence_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                log_curvature_regularization_term=inversion.log_det_curvature_reg_matrix_term,
                log_regularization_term=inversion.log_det_regularization_matrix_term,
                noise_normalization=noise_normalization,
            )

            assert evidence == fit.evidence
            assert evidence == fit.figure_of_merit

            mapped_reconstructed_image = al.util.inversion.mapped_reconstructed_data_from_mapping_matrix_and_reconstruction(
                mapping_matrix=fit.inversion.mapper.mapping_matrix,
                reconstruction=fit.inversion.reconstruction,
            )

            assert (
                fit.inversion.mapped_reconstructed_image.in_1d
                == mapped_reconstructed_image
            ).all()

        def test___lens_fit_galaxy_model_image_dict__profile_images_and_inversion_mapped_reconstructed_image(
            self, masked_interferometer_7
        ):
            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)

            g0 = al.Galaxy(redshift=0.5)
            g1 = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_interferometer_7.grid, sparse_grid=None
            )

            inversion = inversions.InversionInterferometer.from_data_mapper_and_regularization(
                mapper=mapper,
                regularization=reg,
                visibilities=masked_interferometer_7.visibilities,
                noise_map=masked_interferometer_7.noise_map,
                transformer=masked_interferometer_7.transformer,
            )

            assert (fit.galaxy_model_image_dict[g0].in_2d == np.zeros((7, 7))).all()

            assert fit.galaxy_model_image_dict[g1].in_1d == pytest.approx(
                inversion.mapped_reconstructed_image.in_1d, 1.0e-4
            )

        def test___lens_fit_galaxy_model_visibilities_dict__has_inversion_mapped_reconstructed_visibilities(
            self, masked_interferometer_7
        ):
            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)

            g0 = al.Galaxy(redshift=0.5)
            g1 = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_interferometer_7.grid, sparse_grid=None
            )

            inversion = inversions.InversionInterferometer.from_data_mapper_and_regularization(
                mapper=mapper,
                regularization=reg,
                visibilities=masked_interferometer_7.visibilities,
                noise_map=masked_interferometer_7.noise_map,
                transformer=masked_interferometer_7.transformer,
            )

            assert (fit.galaxy_model_visibilities_dict[g0] == np.zeros((7, 2))).all()

            assert fit.galaxy_model_visibilities_dict[g1].in_1d == pytest.approx(
                inversion.mapped_reconstructed_visibilities.in_1d, 1.0e-4
            )

            assert fit.model_visibilities.in_1d == pytest.approx(
                fit.galaxy_model_visibilities_dict[g1].in_1d, 1.0e-4
            )

        def test___all_lens_fit_quantities__hyper_background_noise(
            self, masked_interferometer_7
        ):

            hyper_background_noise = al.hyper_data.HyperBackgroundNoise(noise_scale=1.0)

            hyper_noise_map = hyper_background_noise.hyper_noise_map_from_noise_map(
                noise_map=masked_interferometer_7.noise_map
            )

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=0.01)

            g0 = al.Galaxy(redshift=0.5, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[al.Galaxy(redshift=0.5), g0])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7,
                tracer=tracer,
                hyper_background_noise=hyper_background_noise,
            )

            assert hyper_noise_map.in_1d == pytest.approx(
                fit.inversion.noise_map, 1.0e-4
            )

            assert hyper_noise_map.in_1d == pytest.approx(fit.noise_map.in_1d)

    class TestCompareToManualProfilesAndInversion:
        def test___all_lens_fit_quantities__no_hyper_methods(
            self, masked_interferometer_7
        ):
            galaxy_light = al.Galaxy(
                redshift=0.5, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)
            galaxy_pix = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[galaxy_light, galaxy_pix])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            profile_visibilities = tracer.profile_visibilities_from_grid_and_transformer(
                grid=masked_interferometer_7.grid,
                transformer=masked_interferometer_7.transformer,
            )

            assert profile_visibilities.in_1d == pytest.approx(
                fit.profile_visibilities.in_1d
            )

            profile_subtracted_visibilities = (
                masked_interferometer_7.visibilities - profile_visibilities
            )

            assert profile_subtracted_visibilities.in_1d == pytest.approx(
                fit.profile_subtracted_visibilities.in_1d
            )

            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_interferometer_7.grid, inversion_uses_border=False
            )

            inversion = inversions.InversionInterferometer.from_data_mapper_and_regularization(
                visibilities=profile_subtracted_visibilities,
                noise_map=masked_interferometer_7.noise_map,
                transformer=masked_interferometer_7.transformer,
                mapper=mapper,
                regularization=reg,
            )

            model_visibilities = (
                profile_visibilities + inversion.mapped_reconstructed_visibilities
            )

            assert model_visibilities.in_1d == pytest.approx(
                fit.model_visibilities.in_1d
            )

            residual_map = al.util.fit.residual_map_from_data_and_model_data(
                data=masked_interferometer_7.visibilities, model_data=model_visibilities
            )

            assert residual_map.in_1d == pytest.approx(fit.residual_map.in_1d)

            normalized_residual_map = al.util.fit.normalized_residual_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_interferometer_7.noise_map
            )

            assert normalized_residual_map.in_1d == pytest.approx(
                fit.normalized_residual_map.in_1d
            )

            chi_squared_map = al.util.fit.chi_squared_map_from_residual_map_and_noise_map(
                residual_map=residual_map, noise_map=masked_interferometer_7.noise_map
            )

            assert chi_squared_map.in_1d == pytest.approx(fit.chi_squared_map.in_1d)

            chi_squared = al.util.fit.chi_squared_from_chi_squared_map(
                chi_squared_map=chi_squared_map
            )

            noise_normalization = al.util.fit.noise_normalization_from_noise_map(
                noise_map=masked_interferometer_7.noise_map
            )

            likelihood = al.util.fit.likelihood_from_chi_squared_and_noise_normalization(
                chi_squared=chi_squared, noise_normalization=noise_normalization
            )

            assert likelihood == pytest.approx(fit.likelihood, 1e-4)

            likelihood_with_regularization = al.util.fit.likelihood_with_regularization_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                noise_normalization=noise_normalization,
            )

            assert likelihood_with_regularization == pytest.approx(
                fit.likelihood_with_regularization, 1e-4
            )

            evidence = al.util.fit.evidence_from_inversion_terms(
                chi_squared=chi_squared,
                regularization_term=inversion.regularization_term,
                log_curvature_regularization_term=inversion.log_det_curvature_reg_matrix_term,
                log_regularization_term=inversion.log_det_regularization_matrix_term,
                noise_normalization=noise_normalization,
            )

            assert evidence == fit.evidence
            assert evidence == fit.figure_of_merit

            mapped_reconstructed_image = al.util.inversion.mapped_reconstructed_data_from_mapping_matrix_and_reconstruction(
                mapping_matrix=fit.inversion.mapper.mapping_matrix,
                reconstruction=fit.inversion.reconstruction,
            )

            assert (
                fit.inversion.mapped_reconstructed_image.in_1d
                == mapped_reconstructed_image
            ).all()

        def test___lens_fit_galaxy_model_visibilities_dict__has_profile_image_and_inversion_mapped_reconstructed_image(
            self, masked_interferometer_7
        ):

            g0 = al.Galaxy(
                redshift=0.5, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )
            g1 = al.Galaxy(
                redshift=0.5, light_profile=al.lp.EllipticalSersic(intensity=2.0)
            )
            g2 = al.Galaxy(redshift=0.5)

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)
            galaxy_pix = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2, galaxy_pix])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            traced_grids = tracer.traced_grids_of_planes_from_grid(
                grid=masked_interferometer_7.grid
            )

            g0_visibilities = g0.profile_visibilities_from_grid_and_transformer(
                grid=traced_grids[0], transformer=masked_interferometer_7.transformer
            )

            g1_visibilities = g1.profile_visibilities_from_grid_and_transformer(
                grid=traced_grids[1], transformer=masked_interferometer_7.transformer
            )

            profile_visibilities = g0_visibilities + g1_visibilities

            profile_subtracted_visibilities = (
                masked_interferometer_7.visibilities - profile_visibilities
            )
            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_interferometer_7.grid, inversion_uses_border=False
            )

            inversion = inversions.InversionInterferometer.from_data_mapper_and_regularization(
                visibilities=profile_subtracted_visibilities,
                noise_map=masked_interferometer_7.noise_map,
                transformer=masked_interferometer_7.transformer,
                mapper=mapper,
                regularization=reg,
            )

            g0_image = g0.profile_image_from_grid(grid=traced_grids[0])

            g1_image = g1.profile_image_from_grid(grid=traced_grids[1])

            assert (fit.galaxy_model_image_dict[g2].in_2d == np.zeros((7, 7))).all()

            assert fit.galaxy_model_image_dict[g0].in_1d == pytest.approx(
                g0_image.in_1d, 1.0e-4
            )
            assert fit.galaxy_model_image_dict[g1].in_1d == pytest.approx(
                g1_image.in_1d, 1.0e-4
            )
            assert fit.galaxy_model_image_dict[galaxy_pix].in_1d == pytest.approx(
                inversion.mapped_reconstructed_image.in_1d, 1.0e-4
            )

        def test___lens_fit_galaxy_model_visibilities_dict__has_profile_visibilitiess_and_inversion_mapped_reconstructed_visibilities(
            self, masked_interferometer_7
        ):

            g0 = al.Galaxy(
                redshift=0.5, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )
            g1 = al.Galaxy(
                redshift=0.5, light_profile=al.lp.EllipticalSersic(intensity=2.0)
            )
            g2 = al.Galaxy(redshift=0.5)

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)
            galaxy_pix = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[g0, g1, g2, galaxy_pix])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7, tracer=tracer
            )

            traced_grids = tracer.traced_grids_of_planes_from_grid(
                grid=masked_interferometer_7.grid
            )

            g0_visibilities = g0.profile_visibilities_from_grid_and_transformer(
                grid=traced_grids[0], transformer=masked_interferometer_7.transformer
            )

            g1_visibilities = g1.profile_visibilities_from_grid_and_transformer(
                grid=traced_grids[1], transformer=masked_interferometer_7.transformer
            )

            profile_visibilities = g0_visibilities + g1_visibilities

            profile_subtracted_visibilities = (
                masked_interferometer_7.visibilities - profile_visibilities
            )
            mapper = pix.mapper_from_grid_and_sparse_grid(
                grid=masked_interferometer_7.grid, inversion_uses_border=False
            )

            inversion = inversions.InversionInterferometer.from_data_mapper_and_regularization(
                visibilities=profile_subtracted_visibilities,
                noise_map=masked_interferometer_7.noise_map,
                transformer=masked_interferometer_7.transformer,
                mapper=mapper,
                regularization=reg,
            )

            assert (fit.galaxy_model_visibilities_dict[g2] == np.zeros((7, 2))).all()

            assert fit.galaxy_model_visibilities_dict[g0].in_1d == pytest.approx(
                g0_visibilities.in_1d, 1.0e-4
            )
            assert fit.galaxy_model_visibilities_dict[g1].in_1d == pytest.approx(
                g1_visibilities.in_1d, 1.0e-4
            )
            assert fit.galaxy_model_visibilities_dict[
                galaxy_pix
            ].in_1d == pytest.approx(
                inversion.mapped_reconstructed_visibilities.in_1d, 1.0e-4
            )

            assert fit.model_visibilities.in_1d == pytest.approx(
                fit.galaxy_model_visibilities_dict[g0].in_1d
                + fit.galaxy_model_visibilities_dict[g1].in_1d
                + inversion.mapped_reconstructed_visibilities.in_1d,
                1.0e-4,
            )

        def test___all_lens_fit_quantities__hyper_background_noise(
            self, masked_interferometer_7
        ):

            hyper_background_noise = al.hyper_data.HyperBackgroundNoise(noise_scale=1.0)

            hyper_noise_map = hyper_background_noise.hyper_noise_map_from_noise_map(
                noise_map=masked_interferometer_7.noise_map
            )

            galaxy_light = al.Galaxy(
                redshift=0.5, light_profile=al.lp.EllipticalSersic(intensity=1.0)
            )

            pix = al.pix.Rectangular(shape=(3, 3))
            reg = al.reg.Constant(coefficient=1.0)
            galaxy_pix = al.Galaxy(redshift=1.0, pixelization=pix, regularization=reg)

            tracer = al.Tracer.from_galaxies(galaxies=[galaxy_light, galaxy_pix])

            fit = InterferometerFit(
                masked_interferometer=masked_interferometer_7,
                tracer=tracer,
                hyper_background_noise=hyper_background_noise,
            )

            assert hyper_noise_map.in_1d == pytest.approx(
                fit.inversion.noise_map, 1.0e-4
            )

            assert hyper_noise_map.in_1d == pytest.approx(fit.noise_map.in_1d)


class MockTracerPositions:
    def __init__(self, positions, noise=None):
        self.positions = positions
        self.noise = noise

    def traced_grids_of_planes_from_grid(self, grid, plane_index_limit=None):
        return [self.positions]


class TestPositionsFit:
    def test__x1_positions__mock_position_tracer__maximum_separation_is_correct(self):

        positions = al.coordinates(coordinates=[[(0.0, 0.0), (0.0, 1.0)]])
        tracer = MockTracerPositions(positions=positions)
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separations[0] == 1.0

        positions = al.coordinates([[(0.0, 0.0), (1.0, 1.0)]])
        tracer = MockTracerPositions(positions=positions)
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separations[0] == np.sqrt(2)

        positions = al.coordinates([[(0.0, 0.0), (1.0, 3.0)]])
        tracer = MockTracerPositions(positions=positions)
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separations[0] == np.sqrt(np.square(1.0) + np.square(3.0))

        positions = al.coordinates([[(-2.0, -4.0), (1.0, 3.0)]])
        tracer = MockTracerPositions(positions=positions)
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separations[0] == np.sqrt(np.square(3.0) + np.square(7.0))

        positions = al.coordinates([[(8.0, 4.0), (-9.0, -4.0)]])
        tracer = MockTracerPositions(positions=positions)
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separations[0] == np.sqrt(np.square(17.0) + np.square(8.0))

    def test_multiple_positions__mock_position_tracer__maximum_separation_is_correct(
        self
    ):
        positions = al.coordinates([[(0.0, 0.0), (0.0, 1.0), (0.0, 0.5)]])
        tracer = MockTracerPositions(positions=positions)
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separations[0] == 1.0

        positions = al.coordinates([[(0.0, 0.0), (0.0, 0.0), (3.0, 3.0)]])
        tracer = MockTracerPositions(positions=positions)
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separations[0] == np.sqrt(18)

        al.coordinates([[(0.0, 0.0), (1.0, 1.0), (3.0, 3.0)]])
        tracer = MockTracerPositions(positions=positions)
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separations[0] == np.sqrt(18)

        positions = al.coordinates(
            [
                [
                    (-2.0, -4.0),
                    (1.0, 3.0),
                    (0.1, 0.1),
                    (-0.1, -0.1),
                    (0.3, 0.4),
                    (-0.6, 0.5),
                ]
            ]
        )
        tracer = MockTracerPositions(positions=positions)
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separations[0] == np.sqrt(np.square(3.0) + np.square(7.0))

        positions = al.coordinates([[(8.0, 4.0), (8.0, 4.0), (-9.0, -4.0)]])
        tracer = MockTracerPositions(positions=positions)
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separations[0] == np.sqrt(np.square(17.0) + np.square(8.0))

    def test_multiple_sets_of_positions__multiple_sets_of_max_distances(self):
        positions = al.coordinates(
            [
                [(0.0, 0.0), (0.0, 1.0), (0.0, 0.5)],
                [(0.0, 0.0), (0.0, 0.0), (3.0, 3.0)],
                [(0.0, 0.0), (1.0, 1.0), (3.0, 3.0)],
            ]
        )
        tracer = MockTracerPositions(positions=positions)

        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)

        assert fit.maximum_separations[0] == 1.0
        assert fit.maximum_separations[1] == np.sqrt(18)
        assert fit.maximum_separations[2] == np.sqrt(18)

    def test__likelihood__is_sum_of_separations_divided_by_noise(self):
        positions = al.coordinates(
            [
                [(0.0, 0.0), (0.0, 1.0), (0.0, 0.5)],
                [(0.0, 0.0), (0.0, 0.0), (3.0, 3.0)],
                [(0.0, 0.0), (1.0, 1.0), (3.0, 3.0)],
            ]
        )

        tracer = MockTracerPositions(positions=positions)

        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.chi_squared_map[0] == 1.0
        assert fit.chi_squared_map[1] == pytest.approx(18.0, 1e-4)
        assert fit.chi_squared_map[2] == pytest.approx(18.0, 1e-4)
        assert fit.figure_of_merit == pytest.approx(-0.5 * (1.0 + 18 + 18), 1e-4)

        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=2.0)
        assert fit.chi_squared_map[0] == (1.0 / 2.0) ** 2.0
        assert fit.chi_squared_map[1] == pytest.approx(
            (np.sqrt(18.0) / 2.0) ** 2.0, 1e-4
        )
        assert fit.chi_squared_map[2] == pytest.approx(
            (np.sqrt(18.0) / 2.0) ** 2.0, 1e-4
        )
        assert fit.figure_of_merit == pytest.approx(
            -0.5
            * (
                (1.0 / 2.0) ** 2.0
                + (np.sqrt(18.0) / 2.0) ** 2.0
                + (np.sqrt(18.0) / 2.0) ** 2.0
            ),
            1e-4,
        )

    def test__threshold__if_not_met_returns_ray_tracing_exception(self):

        positions = al.coordinates([[(0.0, 0.0), (0.0, 1.0)]])
        tracer = MockTracerPositions(positions=positions)
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)

        assert fit.maximum_separation_within_threshold(threshold=100.0)
        assert not fit.maximum_separation_within_threshold(threshold=0.1)

    def test__above_with_real_tracer(self):

        tracer = al.Tracer.from_galaxies(
            galaxies=[
                al.Galaxy(
                    redshift=0.5, mass=al.mp.SphericalIsothermal(einstein_radius=1.0)
                ),
                al.Galaxy(redshift=1.0),
            ]
        )

        positions = al.coordinates([[(1.0, 0.0), (-1.0, 0.0)]])
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separation_within_threshold(threshold=0.01)

        positions = al.coordinates([[(1.2, 0.0), (-1.0, 0.0)]])
        fit = al.fit_positions(positions=positions, tracer=tracer, noise_map=1.0)
        assert fit.maximum_separation_within_threshold(threshold=0.3)
        assert not fit.maximum_separation_within_threshold(threshold=0.15)
