from auto_lens.analysis import galaxy
from auto_lens import exc
from auto_lens.profiles import light_profiles, mass_profiles
from auto_lens.analysis.model_mapper import ModelMapper


class GalaxyPrior:
    """
    Class to produce Galaxy instances from sets of profile classes using the model mapper
    """

    def __init__(self, name, model_mapper, align_centres=False, align_orientations=False, **kwargs):
        """
        Parameters
        ----------
        light_profile_classes: [LightProfile]
            The classes for which light profile instances are generated for this galaxy
        mass_profile_classes: [MassProfile]
            The classes for which light profile instances are generated for this galaxy
        align_centres: Bool
            If True the same prior will be used for all the profiles centres such that any generated profiles always
            have the same centre
        align_orientations: Bool
            If True the same prior will be used for all the profiles orientations such that any generated profiles
            always have the same orientation
        """
        self.name = name

        self.light_profile_dict = {"{}_{}".format(name, key): value for key, value in kwargs.items() if
                                   issubclass(value, light_profiles.LightProfile) and not
                                   issubclass(value, mass_profiles.MassProfile)}
        self.mass_profile_dict = {"{}_{}".format(name, key): value for key, value in kwargs.items() if
                                  issubclass(value, mass_profiles.MassProfile)}

        self.align_centres = align_centres
        self.align_orientations = align_orientations

        self.model_mapper = model_mapper

        profile_models = []

        for name, cls in zip(self.light_profile_names, self.light_profile_classes):
            profile_models.append(model_mapper.add_class(name, cls))

        for name, cls in zip(self.mass_profile_names, self.mass_profile_classes):
            profile_models.append(model_mapper.add_class(name, cls))

        if self.align_centres:
            centre = profile_models[0].centre
            for profile_model in profile_models:
                profile_model.centre = centre

        if self.align_orientations:
            phi = profile_models[0].phi
            for profile_model in profile_models:
                profile_model.phi = phi

        self.prior_models = profile_models + [
            model_mapper.add_class(self.redshift_name.format(self.name), galaxy.Redshift)]

    def __getattr__(self, item):
        try:
            return self.__getattribute__(item)
        except AttributeError:
            name = "{}_{}".format(self.name, item)
            return getattr(self.model_mapper, name)

    def override_prior_models(self, **kwargs):
        for key, value in kwargs.items():
            setattr(self.model_mapper, "{}_{}".format(self.name, key), value)

    @property
    def light_profile_classes(self):
        return self.light_profile_dict.values()

    @property
    def light_profile_names(self):
        return list(self.light_profile_dict.keys())

    @property
    def mass_profile_classes(self):
        return self.mass_profile_dict.values()

    @property
    def mass_profile_names(self):
        return list(self.mass_profile_dict.keys())

    @property
    def redshift_name(self):
        """
        Returns
        -------
        redshift_name: String
            The name of the prior associated with redshift for this galaxy.
        """
        return "{}_redshift".format(self.name)

    def galaxy_for_model_instance(self, model_instance):
        """
        Create a galaxy from a model instance that was generated by the associated model mapper.

        Parameters
        ----------
        model_instance: ModelInstance
            A model instance comprising the class instances generated by the model mapper.

        Returns
        -------
        galaxy: Galaxy
            A galaxy generated for this GalaxyPrior
        """
        light_profile_instances = []
        mass_profile_instances = []
        try:
            for name in self.light_profile_names:
                light_profile_instances.append(getattr(model_instance, name))
            for name in self.mass_profile_names:
                mass_profile_instances.append(getattr(model_instance, name))
            redshift = getattr(model_instance, self.redshift_name).redshift
        except AttributeError as e:
            raise exc.PriorException(*e.args)

        return galaxy.Galaxy(light_profiles=light_profile_instances, mass_profiles=mass_profile_instances,
                             redshift=redshift)
